# Test sensor to debug issues
sensor:
  - name: "Test Health Score"
    unique_id: "test_health_score"
    state: >-
      {% set base_score = 85 %}
      {% set hour = now().hour %}
      {% set time_bonus = 5 if 8 <= hour <= 22 else 0 %}
      {{ base_score + time_bonus }}
    unit_of_measurement: "%"
    icon: "mdi:shield-check"
    attributes:
      test_time: "{{ now().strftime('%H:%M on %b %d') }}"
      test_status: "Working"