id: kitchen_morning_lights_on
alias: Kitchen Morning Lights On
description: Morning Water Ration - Dawn Sustenance
trigger:
- platform: state
  entity_id: binary_sensor.kitchen_occupancy
  to: 'on'
condition:
- condition: time
  after: 06:00:00
  before: '10:00:00'
- condition: state
  entity_id: light.ikea_of_sweden_stoftmoln_ceiling_wall_lamp_ww10_light
  state: 'off'
action:
- service: scene.turn_on
  target:
    entity_id: scene.morning_water_ration
- service: notify.mobile_app_tori_phone_2
  data:
    message: Morning water ration prepared. The day's sustenance begins in the sietch.