id: kitchen_late_night_lights
alias: Kitchen Late Night Lights
description: Water Conservation - Late Night Protocol
trigger:
- platform: state
  entity_id: binary_sensor.kitchen_occupancy
  to: 'on'
condition:
- condition: time
  after: '22:15:00'
  before: 06:00:00
action:
- service: scene.turn_on
  target:
    entity_id: scene.energy_conservation
- delay:
    minutes: 10
- service: light.turn_off
  target:
    area_id: kitchen
- service: notify.mobile_app_tori_phone_2
  data:
    message: Water discipline observed. Night conservation protocol active.