alias: "Energy Optimization Climate Control"
description: "Stillsuit energy conservation-based climate adjustments"
mode: single

trigger:
  - platform: numeric_state
    entity_id: sensor.energy_independence_score
    below: 60
    for:
      minutes: 10

variables:
  energy_score: "{{ states('sensor.energy_independence_score') | float(80) }}"
  current_temp: "{{ state_attr('weather.home', 'temperature') or 72 }}"
  occupancy: "{{ is_state('binary_sensor.house_occupied', 'on') }}"

action:
  # Log energy conservation event
  - service: logbook.log
    data:
      name: "Stillsuit Climate Control"
      message: "Energy conservation needed: {{ energy_score }}% independence"

  # Aggressive conservation mode
  - if:
      - condition: template
        value_template: "{{ energy_score < 40 }}"
    then:
      # Emergency conservation
      - service: climate.set_preset_mode
        data:
          entity_id: climate.home
          preset_mode: "eco"

      # Minimal climate control
      - service: climate.set_temperature
        data:
          entity_id: climate.home
          temperature: >
            {% if current_temp > 72 %}
              80
            {% else %}
              62
            {% endif %}

      # Turn off non-essential fans
      - service: fan.turn_off
        target:
          area_id: ["bedroom", "office"]

      # Critical conservation notification
      - service: notify.mobile_app_tori_phone_2
        data:
          title: "⚡ Stillsuit: CRITICAL Energy Conservation"
          message: >
            Energy independence critical at {{ energy_score }}%.
            Emergency climate conservation protocols activated.
            Minimal comfort systems only.

  # Standard conservation mode
  - if:
      - condition: template
        value_template: "{{ energy_score >= 40 and energy_score < 60 }}"
    then:
      # Moderate conservation
      - service: climate.set_preset_mode
        data:
          entity_id: climate.home
          preset_mode: "eco"

      # Reduce fan usage
      - service: fan.set_percentage
        target:
          area_id: ["living_room", "bedroom", "office"]
        data:
          percentage: 30

      # Conservation notification
      - service: notify.mobile_app_tori_phone_2
        data:
          title: "🔋 Stillsuit: Energy Conservation"
          message: >
            Energy independence at {{ energy_score }}%.
            Conservation protocols engaged.
            Comfort systems reduced for efficiency.