id: garage_door_open_on_motion
alias: Garage Door Open on Motion
description: Ornithopter Departure - Desert Patrol Ready
trigger:
- platform: state
  entity_id: binary_sensor.garage_motion
  to: 'on'
condition:
- condition: state
  entity_id: cover.garage_door
  state: closed
- condition: time
  after: 06:00:00
  before: '22:00:00'
action:
- service: cover.open_cover
  target:
    entity_id: cover.garage_door
- service: light.turn_on
  target:
    entity_id: light.garage_lights
  data:
    brightness: 255
- service: notify.mobile_app_tori_phone_2
  data:
    message: Ornithopter bay opens. May your flight carry you safely across the
      deep desert.