id: garage_door_close_after_motion_stops
alias: Garage Door Close After Motion Stops
description: Ornithopter Secured - Bay Sealed
area_id: garage
trigger:
- platform: state
  entity_id: binary_sensor.garage_motion
  to: 'off'
  for: 00:05:00
condition:
- condition: state
  entity_id: cover.garage_door
  state: open
action:
- service: cover.close_cover
  target:
    entity_id: cover.garage_door
- delay: 00:02:00
- service: light.turn_off
  target:
    entity_id: light.garage_lights
- service: notify.mobile_app_tori_phone_2
  data:
    message: Desert patrol complete. Ornithopter secured in hangar sanctuary.