---
# Dawn Awakening Report - Daily Morning Status
alias: "Dawn Awakening Report"
description: "Comprehensive morning status report with overnight analysis and daily preparation guidance"
trigger:
  - platform: time
    at: "07:00:00"
condition:
  - condition: state
    entity_id: input_boolean.notification_system_enabled
    state: "on"
    for:
      seconds: 30
action:
  - service: notify.mobile_app_tori_phone_2
    data:
      title: "🌅 Dawn Breaks Over Sietch Tabr"
      message: >-
        Dawn awakening, Muad'Dib. The desert night yields to the sun.
        
        📊 **Sietch Vitals:**
        • Health Score: {{ states('sensor.sietch_health_score') }}% - {{ state_attr('sensor.sietch_health_score', 'status_level') }}
        • Night Security: {{ states('sensor.night_security_effectiveness') }}% - {{ state_attr('sensor.night_security_effectiveness', 'threat_level') }}
        • Desert Survival: {{ states('sensor.desert_survival_status') }} {{ state_attr('sensor.desert_survival_status', 'survival_rating') }}
        
        💧 **Water Conservation:**
        Conservation Index: {{ states('sensor.water_conservation_index') }}%
        Status: {{ state_attr('sensor.water_conservation_index', 'conservation_level') }}
        Night efficiency maintained throughout the stillsuit hours.
        
        ⚡ **Energy Systems:**
        • Shield Status: {{ states('sensor.energy_shield_status') }}% - {{ state_attr('sensor.energy_shield_status', 'shield_strength') }}
        • Harvester Efficiency: {{ states('sensor.harvester_efficiency') }}% - {{ state_attr('sensor.harvester_efficiency', 'efficiency_grade') }}
        
        🤖 **Automation Intelligence:**
        Success Rate: {{ states('sensor.automation_success_rate') }}% - {{ state_attr('sensor.automation_success_rate', 'success_grade') }}
        {{ state_attr('sensor.automation_success_rate', 'enabled_automations') }}/{{ state_attr('sensor.automation_success_rate', 'total_automations') }} systems operational
        
        🏃 **Activity Preparation:**
        • Morning Ritual: {{ states('sensor.morning_ritual_completion') }}% - {{ state_attr('sensor.morning_ritual_completion', 'ritual_phase') }}
        • Expected Activity: {{ state_attr('sensor.fremen_activity_level', 'current_period') }}
        
        The spice flows, and your domain prospers. Begin the day's work with the blessing of Shai-Hulud.
      data:
        actions:
          - action: "VIEW_SIETCH_STATUS"
            title: "📊 Full Sietch Status"
          - action: "MORNING_ROUTINE_START"
            title: "🌅 Begin Morning Ritual"
        group: "daily_reports"
        tag: "dawn_report"
        notification_icon: "mdi:weather-sunrise"
        color: "#FF6B35"
        channel: "Sietch Reports"
        importance: high
        sticky: false
        timeout: 1800
  
  # Send to persistent notification for dashboard
  - service: persistent_notification.create
    data:
      title: "🌅 Dawn Awakening Complete"
      message: >-
        **Sietch Status:** {{ states('sensor.sietch_health_score') }}% Health | {{ states('sensor.water_conservation_index') }}% Conservation
        
        **Night Analysis:** {{ state_attr('sensor.night_security_effectiveness', 'threat_level') }}
        **Today's Focus:** {{ state_attr('sensor.fremen_activity_level', 'current_period') }}
        
        *The desert protects those who respect its power.*
      notification_id: "dawn_awakening_{{ now().strftime('%Y%m%d') }}"

mode: single
max_exceeded: silent