---
# Harvester Efficiency Warning System - Spice Production Alerts
alias: "Harvester Efficiency Warning System"
description: "Intelligent harvester monitoring with production optimization alerts"
trigger:
  - platform: numeric_state
    entity_id: sensor.harvester_efficiency
    below: 70
    for:
      minutes: 8
    id: efficiency_warning
  - platform: numeric_state
    entity_id: sensor.harvester_efficiency
    below: 50
    for:
      minutes: 3
    id: efficiency_critical
  - platform: numeric_state
    entity_id: sensor.harvester_efficiency
    below: 30
    for:
      minutes: 1
    id: efficiency_emergency
  - platform: numeric_state
    entity_id: sensor.harvester_efficiency
    above: 90
    for:
      minutes: 10
    id: efficiency_optimal
  - platform: template
    value_template: >-
      {{ states('sensor.harvester_efficiency') | float < 60 and
         (now().hour >= 8 and now().hour <= 22) }}
    id: peak_hour_inefficiency
condition:
  - condition: state
    entity_id: input_boolean.notification_system_enabled
    state: "on"
action:
  - choose:
      # HARVESTER EMERGENCY - Production Failure
      - conditions:
          - condition: trigger
            id: efficiency_emergency
        sequence:
          - service: notify.mobile_app_tori_phone_2
            data:
              title: "🚨 HARVESTER EMERGENCY: Production Failure!"
              message: >-
                GUILD NAVIGATOR ALERT! The spice harvest fails catastrophically!
                
                ⚡ **CRITICAL EFFICIENCY**: {{ states('sensor.harvester_efficiency') }}% - {{ state_attr('sensor.harvester_efficiency', 'efficiency_grade') }}
                📉 **PRODUCTION STATUS**: EMERGENCY SHUTDOWN IMMINENT
                
                **Harvester Analysis:**
                • Current Load: {{ state_attr('sensor.harvester_efficiency', 'current_load') }}
                • Motion Activity: {{ state_attr('sensor.harvester_efficiency', 'motion_activity') }}
                • Peak Hours: {{ state_attr('sensor.harvester_efficiency', 'peak_hours') }}
                
                **Critical Impact Assessment:**
                • Spice Production: {{ states('sensor.spice_production_level') }} units ({{ state_attr('sensor.spice_production_level', 'current_yield') }})
                • Guild Rating: {{ state_attr('sensor.spice_production_level', 'guild_rating') }}
                • System Health Impact: {{ states('sensor.sietch_health_score') }}%
                
                🏜️ "He who controls the spice controls the universe. Your control slips away!"
                
                **EMERGENCY PROTOCOLS:**
                • Immediate harvester system review required
                • Check for mechanical failures or blockages
                • Verify power distribution and load balancing
                • Inspect motion sensor network integrity
                
                THE GUILD DEMANDS THE SPICE MUST FLOW! ACT IMMEDIATELY OR FACE THE CONSEQUENCES!
              data:
                actions:
                  - action: "HARVESTER_EMERGENCY_REPAIR"
                    title: "🔧 Emergency Repair"
                  - action: "SPICE_PRODUCTION_OVERRIDE"
                    title: "⚡ Production Override"
                  - action: "GUILD_NOTIFICATION"
                    title: "📡 Notify Guild"
                group: "harvester_emergency"
                tag: "harvester_critical"
                notification_icon: "mdi:factory-alert"
                color: "#8B0000"
                channel: "Harvester Alerts"
                importance: max
                sticky: true
                timeout: 0
                sound: "alarm_stream_max_4"

          - service: persistent_notification.create
            data:
              title: "🚨 HARVESTER EMERGENCY ACTIVE"
              message: >-
                **CRITICAL SPICE PRODUCTION FAILURE**
                
                Efficiency: {{ states('sensor.harvester_efficiency') }}%
                Grade: {{ state_attr('sensor.harvester_efficiency', 'efficiency_grade') }}
                
                **THE SPICE MUST FLOW - IMMEDIATE ACTION REQUIRED**
                
                Time: {{ now().strftime('%H:%M:%S') }}
              notification_id: "harvester_emergency"

      # CRITICAL EFFICIENCY ALERT
      - conditions:
          - condition: trigger
            id: efficiency_critical
        sequence:
          - service: notify.mobile_app_tori_phone_2
            data:
              title: "⚠️ CRITICAL: Harvester Efficiency Degraded"
              message: >-
                The spice harvest suffers, Muad'Dib. The Guild will notice such inefficiency.
                
                ⚡ **Harvester Efficiency**: {{ states('sensor.harvester_efficiency') }}% - {{ state_attr('sensor.harvester_efficiency', 'efficiency_grade') }}
                📊 **Production Impact**: {{ states('sensor.spice_production_level') }} units ({{ state_attr('sensor.spice_production_level', 'current_yield') }})
                
                **Efficiency Analysis:**
                • System Load: {{ state_attr('sensor.harvester_efficiency', 'current_load') }}
                • Activity Zones: {{ state_attr('sensor.harvester_efficiency', 'motion_activity') }}
                • Peak Performance Window: {{ state_attr('sensor.harvester_efficiency', 'peak_hours') }}
                
                **Contributing Factors:**
                {% if (now().hour < 8 or now().hour > 22) %}• Operating outside peak efficiency hours{% endif %}
                {% if state_attr('sensor.harvester_efficiency', 'current_load') | replace(' active devices', '') | int > 8 %}• Excessive system load detected{% endif %}
                
                **Production Metrics:**
                • Current Guild Rating: {{ state_attr('sensor.spice_production_level', 'guild_rating') }}
                • Spice Yield Status: {{ state_attr('sensor.spice_production_level', 'current_yield') }}
                
                🏜️ "The desert provides, but only to those who respect its rhythms. Your harvesters struggle against natural patterns."
                
                **Corrective Actions:**
                • Optimize harvester load distribution
                • Review motion sensor network performance
                • Balance system resource allocation
                • Consider maintenance protocols
                
                The Guild watches. The Baron waits. Restore efficiency before competitors sense weakness.
              data:
                actions:
                  - action: "HARVESTER_DIAGNOSTICS"
                    title: "🔍 Run Diagnostics"
                  - action: "OPTIMIZE_HARVESTER"
                    title: "⚙️ Optimize Systems"
                  - action: "PRODUCTION_ANALYSIS"
                    title: "📊 Production Report"
                group: "harvester_alerts"
                tag: "harvester_critical"
                notification_icon: "mdi:factory-alert"
                color: "#E67E22"
                channel: "Harvester Alerts"
                importance: high
                sticky: true
                timeout: 1800

      # STANDARD EFFICIENCY WARNING
      - conditions:
          - condition: trigger
            id: efficiency_warning
        sequence:
          - service: notify.mobile_app_tori_phone_2
            data:
              title: "⚠️ Harvester Efficiency Below Standards"
              message: >-
                Harvester performance declines, Duke. The spice flow requires attention.
                
                ⚡ **Current Efficiency**: {{ states('sensor.harvester_efficiency') }}% - {{ state_attr('sensor.harvester_efficiency', 'efficiency_grade') }}
                📈 **Trend**: Below optimal operating parameters
                
                **Performance Metrics:**
                • Production Level: {{ states('sensor.spice_production_level') }} units
                • Current Yield: {{ state_attr('sensor.spice_production_level', 'current_yield') }}
                • Guild Rating: {{ state_attr('sensor.spice_production_level', 'guild_rating') }}
                
                **System Analysis:**
                • Device Load: {{ state_attr('sensor.harvester_efficiency', 'current_load') }}
                • Zone Activity: {{ state_attr('sensor.harvester_efficiency', 'motion_activity') }}
                • Optimal Hours: {{ state_attr('sensor.harvester_efficiency', 'peak_hours') }}
                
                🏜️ **Operation Guidance:**
                "Efficiency in spice production requires harmony between machine and desert rhythms."
                
                **Optimization Opportunities:**
                {% if (now().hour >= 8 and now().hour <= 22) %}• Operating within peak hours - efficiency should be higher{% endif %}
                • Review current system load distribution
                • Optimize motion-based automation triggers
                • Consider harvester maintenance scheduling
                
                Maintain focus. The universe depends on the spice, and the spice depends on your vigilance.
              data:
                actions:
                  - action: "VIEW_EFFICIENCY_TRENDS"
                    title: "📈 View Trends"
                  - action: "OPTIMIZATION_GUIDE"
                    title: "💡 Optimization Tips"
                  - action: "SCHEDULE_MAINTENANCE"
                    title: "🔧 Schedule Maintenance"
                group: "harvester_alerts"
                tag: "harvester_warning"
                notification_icon: "mdi:factory"
                color: "#F39C12"
                channel: "Harvester Alerts"
                importance: default
                sticky: false
                timeout: 1200

      # OPTIMAL EFFICIENCY ACHIEVEMENT
      - conditions:
          - condition: trigger
            id: efficiency_optimal
        sequence:
          - service: notify.mobile_app_tori_phone_2
            data:
              title: "🏆 Optimal Harvester Performance!"
              message: >-
                Magnificent, Muad'Dib! Your harvesters achieve Guild Navigator standards.
                
                ⚡ **Peak Efficiency**: {{ states('sensor.harvester_efficiency') }}% - {{ state_attr('sensor.harvester_efficiency', 'efficiency_grade') }}
                🌟 **Performance Grade**: {{ state_attr('sensor.harvester_efficiency', 'efficiency_grade') }}
                
                **Production Excellence:**
                • Spice Production: {{ states('sensor.spice_production_level') }} units
                • Yield Status: {{ state_attr('sensor.spice_production_level', 'current_yield') }}
                • Guild Recognition: {{ state_attr('sensor.spice_production_level', 'guild_rating') }}
                
                **Operational Mastery:**
                • System Load Optimization: Excellent
                • Motion Synchronization: {{ state_attr('sensor.harvester_efficiency', 'motion_activity') }}
                • Peak Hour Utilization: Maximized
                
                🏜️ **Guild Commendation**: "Your harvesters move with the desert's rhythm. The spice flows as Shai-Hulud intended."
                
                **Benefits of Peak Performance:**
                • Enhanced spice production output
                • Improved system-wide efficiency ratings
                • Reduced mechanical stress and maintenance needs
                • Guild favor and trading advantages
                
                {% if states('sensor.harvester_efficiency') | float >= 95 %}
                🌟 **LEGENDARY ACHIEVEMENT**: Harvester efficiency exceeds even the most optimistic Guild projections!
                {% endif %}
                
                The desert recognizes mastery. Your domain prospers under such excellence.
              data:
                actions:
                  - action: "VIEW_PEAK_PERFORMANCE"
                    title: "📊 Performance Report"
                  - action: "GUILD_COMMENDATION"
                    title: "🏅 Guild Report"
                  - action: "MAINTAIN_EXCELLENCE"
                    title: "⚙️ Maintain Standards"
                group: "achievements"
                tag: "harvester_optimal"
                notification_icon: "mdi:trophy"
                color: "#27AE60"
                channel: "Achievements"
                importance: default
                sticky: false
                timeout: 900

      # PEAK HOUR INEFFICIENCY ALERT
      - conditions:
          - condition: trigger
            id: peak_hour_inefficiency
        sequence:
          - service: notify.mobile_app_tori_phone_2
            data:
              title: "⏰ Peak Hour Inefficiency Detected"
              message: >-
                The prime harvest hours waste away, Duke. This inefficiency costs valuable spice production.
                
                ⚡ **Current Efficiency**: {{ states('sensor.harvester_efficiency') }}%
                ⏰ **Peak Hours Active**: {{ state_attr('sensor.harvester_efficiency', 'peak_hours') }}
                
                **Lost Opportunity Analysis:**
                • Expected Efficiency: 85-95% during peak hours
                • Current Performance: {{ state_attr('sensor.harvester_efficiency', 'efficiency_grade') }}
                • Production Impact: {{ state_attr('sensor.spice_production_level', 'current_yield') }}
                
                🏜️ "Time is the fire in which we burn. Do not waste the precious daylight hours when the desert offers its greatest gifts."
                
                **Immediate Optimization:**
                • Review current system load
                • Optimize motion-triggered operations
                • Reduce non-essential energy consumption
                
                Seize the peak hours. The desert will not offer this efficiency window again until tomorrow.
              data:
                actions:
                  - action: "PEAK_HOUR_OPTIMIZATION"
                    title: "⚡ Optimize Now"
                  - action: "VIEW_PEAK_ANALYSIS"
                    title: "📊 Peak Analysis"
                group: "harvester_alerts"
                tag: "peak_inefficiency"
                notification_icon: "mdi:clock-alert"
                color: "#9B59B6"
                channel: "Harvester Alerts"
                importance: default
                sticky: false
                timeout: 900

mode: queued
max: 10
max_exceeded: silent