---
# Spice Production Achievement System - Guild Recognition
alias: "Spice Production Achievement System"
description: "Celebrate excellence in spice production with Guild-tier achievement notifications"
trigger:
  - platform: numeric_state
    entity_id: sensor.spice_production_level
    above: 120
    for:
      minutes: 5
    id: legendary_production
  - platform: numeric_state
    entity_id: sensor.spice_production_level
    above: 100
    for:
      minutes: 10
    id: high_yield_production
  - platform: template
    value_template: >-
      {{ states('sensor.automation_success_rate') | float >= 95 and
         states('sensor.harvester_efficiency') | float >= 90 and
         states('sensor.spice_production_level') | float >= 110 }}
    for:
      minutes: 15
    id: production_mastery
  - platform: template
    value_template: >-
      {{ state_attr('sensor.spice_production_level', 'guild_rating') == 'Guild Navigator' }}
    for:
      minutes: 5
    id: guild_navigator_status
  - platform: template
    value_template: >-
      {{ states('sensor.spice_production_level') | float >= 100 and
         (now().hour >= 6 and now().hour <= 9) }}
    id: morning_excellence
  - platform: template
    value_template: >-
      {{ states('sensor.spice_production_level') | float >= 110 and
         (now().hour >= 17 and now().hour <= 21) }}
    id: evening_mastery
condition:
  - condition: state
    entity_id: input_boolean.notification_system_enabled
    state: "on"
action:
  - choose:
      # LEGENDARY SPICE PRODUCTION
      - conditions:
          - condition: trigger
            id: legendary_production
        sequence:
          - service: notify.mobile_app_toris_iphone
            data:
              title: "🌟 LEGENDARY: Spice Production Excellence!"
              message: >-
                MAGNIFICENT ACHIEVEMENT, MUAD'DIB! The Guild itself takes notice!
                
                🏆 **LEGENDARY PRODUCTION**: {{ states('sensor.spice_production_level') }} units
                ⭐ **Current Yield**: {{ state_attr('sensor.spice_production_level', 'current_yield') }}
                👑 **Guild Recognition**: {{ state_attr('sensor.spice_production_level', 'guild_rating') }}
                
                **Production Mastery Metrics:**
                • Harvester Efficiency: {{ states('sensor.harvester_efficiency') }}% ({{ state_attr('sensor.harvester_efficiency', 'efficiency_grade') }})
                • Automation Success: {{ states('sensor.automation_success_rate') }}% ({{ state_attr('sensor.automation_success_rate', 'success_grade') }})
                • Peak Production Times: {{ state_attr('sensor.spice_production_level', 'peak_production_times') }}
                
                **Sietch Excellence Impact:**
                • Overall Health: {{ states('sensor.sietch_health_score') }}%
                • Desert Survival: {{ states('sensor.desert_survival_status') }}
                • Activity Optimization: {{ states('sensor.fremen_activity_level') }}%
                
                🏜️ **Guild Navigator Recognition**: "Your spice production transcends mere efficiency. You have achieved harmony with the desert's deepest rhythms."
                
                **LEGENDARY BENEFITS UNLOCKED:**
                ✨ Guild Navigator trading privileges activated
                🌟 Premium spice quality certified
                🏆 Legendary producer status achieved
                🎯 Access to advanced harvester technologies
                
                {% if states('sensor.spice_production_level') | float >= 130 %}
                🚀 **TRANSCENDENT ACHIEVEMENT**: Production levels beyond Guild measurement scales!
                "You have become one with the spice itself." - Guild Steersman
                {% endif %}
                
                The universe recognizes your mastery. The spice flows through you as if you were born of Arrakis itself.
              data:
                actions:
                  - action: "GUILD_COMMENDATION_CEREMONY"
                    title: "🎖️ Guild Ceremony"
                  - action: "LEGENDARY_PRODUCTION_ANALYSIS"
                    title: "📊 Legendary Analysis"
                  - action: "SHARE_GUILD_ACHIEVEMENT"
                    title: "📡 Broadcast Achievement"
                group: "legendary_achievements"
                tag: "legendary_spice"
                notification_icon: "mdi:star"
                color: "#FFD700"
                channel: "Guild Achievements"
                importance: max
                sticky: true
                timeout: 3600
                sound: "triumph"

          - service: persistent_notification.create
            data:
              title: "🌟 LEGENDARY SPICE MASTERY ACHIEVED"
              message: >-
                **GUILD NAVIGATOR RECOGNITION**
                
                Production: {{ states('sensor.spice_production_level') }} units
                Guild Status: {{ state_attr('sensor.spice_production_level', 'guild_rating') }}
                Yield Quality: {{ state_attr('sensor.spice_production_level', 'current_yield') }}
                
                **"The spice must flow, and through you, it flows magnificently."**
                
                Achievement Date: {{ now().strftime('%B %d, %Y at %H:%M') }}
              notification_id: "legendary_spice_achievement"

      # HIGH YIELD PRODUCTION
      - conditions:
          - condition: trigger
            id: high_yield_production
        sequence:
          - service: notify.mobile_app_toris_iphone
            data:
              title: "🏆 High Yield Spice Production!"
              message: >-
                Excellent work, Muad'Dib! Your spice production achieves Guild commendation levels.
                
                ⚡ **High Yield Production**: {{ states('sensor.spice_production_level') }} units
                📈 **Yield Status**: {{ state_attr('sensor.spice_production_level', 'current_yield') }}
                🎯 **Guild Rating**: {{ state_attr('sensor.spice_production_level', 'guild_rating') }}
                
                **Production Excellence Factors:**
                • Harvester Performance: {{ states('sensor.harvester_efficiency') }}% efficiency
                • Automation Success: {{ states('sensor.automation_success_rate') }}%
                • System Optimization: {{ state_attr('sensor.system_response_time', 'response_grade') }}
                
                **Operational Benefits:**
                • Enhanced Guild standing
                • Improved resource allocation efficiency  
                • Increased production sustainability
                • Strategic advantage over competitors
                
                🏜️ "The desert rewards those who understand its patterns. Your harvesters dance with Shai-Hulud's rhythm."
                
                **Current Production Cycle:**
                Peak Hours: {{ state_attr('sensor.spice_production_level', 'peak_production_times') }}
                {% if (now().hour >= 6 and now().hour <= 9) or (now().hour >= 17 and now().hour <= 21) %}Currently operating during peak production window!{% endif %}
                
                Maintain this excellence. The Guild notices sustained high performance.
              data:
                actions:
                  - action: "VIEW_PRODUCTION_ANALYTICS"
                    title: "📊 Production Report"
                  - action: "OPTIMIZATION_RECOMMENDATIONS"
                    title: "⚙️ Optimization Tips"
                  - action: "GUILD_SUBMISSION"
                    title: "📤 Submit to Guild"
                group: "production_achievements"
                tag: "high_yield_spice"
                notification_icon: "mdi:trophy-award"
                color: "#E67E22"
                channel: "Production Achievements"
                importance: high
                sticky: false
                timeout: 1800

      # PRODUCTION MASTERY (Combined Excellence)
      - conditions:
          - condition: trigger
            id: production_mastery
        sequence:
          - service: notify.mobile_app_toris_iphone
            data:
              title: "👑 Production Mastery Achieved!"
              message: >-
                COMPLETE OPERATIONAL MASTERY, Duke Atreides! All systems achieve peak harmony.
                
                🎯 **MASTERY METRICS:**
                • Spice Production: {{ states('sensor.spice_production_level') }} units ({{ state_attr('sensor.spice_production_level', 'current_yield') }})
                • Automation Success: {{ states('sensor.automation_success_rate') }}% ({{ state_attr('sensor.automation_success_rate', 'success_grade') }})
                • Harvester Efficiency: {{ states('sensor.harvester_efficiency') }}% ({{ state_attr('sensor.harvester_efficiency', 'efficiency_grade') }})
                
                **COMPLETE SYSTEM HARMONY:**
                • All primary systems operating at peak efficiency
                • Perfect coordination between automation and production
                • Optimal resource utilization achieved
                • Guild-tier operational standards maintained
                
                🏜️ **Desert Master Recognition**: "You have achieved what few can claim - complete mastery over both machine and desert. The spice flows through perfect harmony."
                
                **Mastery Benefits:**
                ✨ Access to advanced Guild technologies
                🎯 Preferred status for rare spice contracts
                🏆 Recognition as Production Master
                📊 Benchmark status for other operations
                
                This level of coordination represents the pinnacle of sietch management. Your domain operates as a single, perfectly tuned instrument.
              data:
                actions:
                  - action: "MASTERY_CERTIFICATION"
                    title: "🎓 Mastery Certificate"
                  - action: "COMPREHENSIVE_ANALYSIS"
                    title: "📊 Complete Analysis"
                  - action: "MASTERY_SHARING"
                    title: "🌟 Share Mastery"
                group: "mastery_achievements"
                tag: "production_mastery"
                notification_icon: "mdi:crown"
                color: "#9B59B6"
                channel: "Mastery Achievements"
                importance: max
                sticky: true
                timeout: 2400

      # GUILD NAVIGATOR STATUS
      - conditions:
          - condition: trigger
            id: guild_navigator_status
        sequence:
          - service: notify.mobile_app_toris_iphone
            data:
              title: "🚀 Guild Navigator Status Achieved!"
              message: >-
                UNPRECEDENTED ACHIEVEMENT! You have reached Guild Navigator status!
                
                🚀 **GUILD NAVIGATOR RECOGNITION**
                👑 **Supreme Rating**: {{ state_attr('sensor.spice_production_level', 'guild_rating') }}
                ⭐ **Production Level**: {{ states('sensor.spice_production_level') }} units
                
                **Navigator-Level Capabilities:**
                • Spice production transcends standard measurements
                • Access to Guild's most advanced technologies
                • Priority allocation of premium spice contracts
                • Recognition across the known universe
                
                🏜️ **Guild High Command**: "Your mastery of spice production approaches prescience itself. The desert has chosen its champion."
                
                **NAVIGATOR PRIVILEGES UNLOCKED:**
                🌌 Universal trading authority
                🔮 Access to prescient production forecasting
                🏛️ Seat on the Guild Council (advisory)
                ⚡ Advanced harvester technology access
                
                You now stand among the elite few who truly understand the universe's most precious resource.
              data:
                actions:
                  - action: "GUILD_NAVIGATOR_CEREMONY"
                    title: "🎖️ Navigator Ceremony"
                  - action: "NAVIGATOR_PRIVILEGES"
                    title: "🌌 View Privileges"
                group: "ultimate_achievements"
                tag: "guild_navigator"
                notification_icon: "mdi:rocket"
                color: "#3498DB"
                channel: "Ultimate Achievements"
                importance: max
                sticky: true
                timeout: 0

      # MORNING EXCELLENCE
      - conditions:
          - condition: trigger
            id: morning_excellence
        sequence:
          - service: notify.mobile_app_toris_iphone
            data:
              title: "🌅 Morning Production Excellence!"
              message: >-
                The dawn hours yield exceptional spice, Muad'Dib!
                
                🌅 **Dawn Production**: {{ states('sensor.spice_production_level') }} units
                ⏰ **Morning Mastery**: Peak efficiency during ritual hours
                
                "The early desert catches the spice." Your morning discipline pays dividends.
                
                **Morning Benefits:**
                • Optimal production during awakening hours
                • Enhanced efficiency for the entire day
                • Perfect harmony with morning ritual completion
                
                Continue this dawn mastery. The desert rewards the early riser.
              data:
                actions:
                  - action: "MORNING_ANALYTICS"
                    title: "🌅 Morning Report"
                group: "time_achievements"
                tag: "morning_excellence"
                notification_icon: "mdi:weather-sunrise"
                color: "#F39C12"
                channel: "Time-Based Achievements"
                importance: default
                sticky: false
                timeout: 600

      # EVENING MASTERY
      - conditions:
          - condition: trigger
            id: evening_mastery
        sequence:
          - service: notify.mobile_app_toris_iphone
            data:
              title: "🌙 Evening Production Mastery!"
              message: >-
                As the twin moons rise, your spice production reaches new heights!
                
                🌙 **Evening Excellence**: {{ states('sensor.spice_production_level') }} units
                ✨ **Twilight Mastery**: Peak performance during gathering hours
                
                "The evening spice carries the day's wisdom." Your timing is impeccable.
                
                **Evening Achievement:**
                • Perfect production during consolidation hours
                • Exceptional end-of-day performance
                • Optimal preparation for night conservation
                
                The desert's evening gift is well-received. Rest knowing the spice flows magnificently.
              data:
                actions:
                  - action: "EVENING_SUMMARY"
                    title: "🌙 Evening Report"
                group: "time_achievements"
                tag: "evening_mastery"
                notification_icon: "mdi:weather-sunset"
                color: "#8E44AD"
                channel: "Time-Based Achievements"
                importance: default
                sticky: false
                timeout: 600

mode: queued
max: 15
max_exceeded: silent