blueprint:
  name: Appliance Cycle Tracking
  description: Track appliance cycles with datetime updates and Dune-themed notifications
  domain: automation
  input:
    appliance_name:
      name: Appliance Name
      description: Display name of the appliance (e.g., "Dryer", "Washer")
      selector:
        text:
    input_boolean_entity:
      name: Input Boolean Entity
      description: The input boolean entity that tracks appliance state
      selector:
        entity:
          domain: input_boolean
    datetime_helper:
      name: Datetime Helper
      description: Input datetime helper to update with timestamp (optional for completion cycles)
      default: ""
      selector:
        entity:
          domain: input_datetime
    notification_target:
      name: Notification Target
      description: Mobile app notification target
      selector:
        device:
          integration: mobile_app
    cycle_type:
      name: Cycle Type
      description: Type of cycle tracking (started or completed)
      default: started
      selector:
        select:
          options:
            - started
            - completed
    trigger_state:
      name: Trigger State
      description: State change that triggers the automation
      default: "on"
      selector:
        select:
          options:
            - "on"
            - "off"
    custom_message:
      name: Custom Message
      description: Custom Dune-themed notification message
      selector:
        text:
          multiline: true
    dune_description:
      name: Dune Description
      description: Dune-themed description for the automation
      selector:
        text:

trigger:
  - platform: state
    entity_id: !input input_boolean_entity
    to: !input trigger_state

condition: []

action:
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ datetime_helper != '' and datetime_helper != none }}"
        sequence:
          - service: input_datetime.set_datetime
            target:
              entity_id: !input datetime_helper
            data:
              datetime: "{{ now() }}"
  - service: notify.mobile_app_tori_phone_2
    data:
      message: !input custom_message

variables:
  appliance_name: !input appliance_name
  cycle_type: !input cycle_type
  notification_target: !input notification_target
  datetime_helper: !input datetime_helper

mode: single