id: evening_sunset_routine
alias: Evening Sunset Routine
description: Sunset Over Arrakis - Evening Protocol
triggers:
- event: sunset
  offset: -00:30:00
  trigger: sun
actions:
- action: scene.turn_on
  data: {}
  target:
    entity_id: scene.sunset_over_arrakis_evening_routine
- data:
    message: Sunset graces Arrakis. Sietch secured for evening. Desert companions
      comfortable.
  action: notify.mobile_app_tori_phone_2