id: nighttime_security_mode
alias: Nighttime Security Mode
description: Night Watch Begins - Sietch Security
trigger:
- platform: time
  at: '22:00:00'
action:
- service: input_boolean.turn_on
  target:
    entity_id: input_boolean.enhanced_security_mode
- service: scene.turn_on
  target:
    entity_id: scene.energy_conservation
- service: script.turn_on
  target:
    entity_id: script.night_security_protocol