id: pet_activity_tracking
alias: Pet Activity Tracking
description: Atlas Activity Analysis - Desert Guide Status
trigger:
- platform: time
  at: '20:00:00'
action:
- service: counter.increment
  target:
    entity_id: counter.atlas_daily_motion
- service: notify.mobile_app_tori_phone_2
  data:
    message: 'Muad''Dib (Atlas) activity: {{ states(''sensor.atlas_motion_events_today'')
      }} desert movements today. Guide remains vigilant.'