id: washer_cycle_started
alias: Washer Cycle Started
description: Water Discipline Protocol - Wash Cycle Begin
trigger:
- platform: state
  entity_id: input_boolean.washer_cycle_active
  to: 'on'
action:
- service: input_datetime.set_datetime
  target:
    entity_id: input_datetime.last_wash_started
  data:
    datetime: '{{ now() }}'
- service: notify.mobile_app_tori_phone_2
  data:
    message: Water discipline protocol initiated. Sacred moisture flows through
      reclamation systems.