alias: "Alexa Timer Smart Responses"
description: "Intelligent responses and actions when Alexa timers are set or expire with context-aware automation"
trigger:
  # Timer started events
  - platform: state
    entity_id: 
      - sensor.echo_dot_kitchen_next_timer
      - sensor.echo_dot_atlas_room_next_timer
      - sensor.bose_bedroom_next_timer
      - sensor.bose_office_next_timer
    to: 
    from: "unavailable"
    id: "timer_started"
  
  # Timer ended events
  - platform: state
    entity_id:
      - sensor.echo_dot_kitchen_next_timer
      - sensor.echo_dot_atlas_room_next_timer
      - sensor.bose_bedroom_next_timer
      - sensor.bose_office_next_timer
    to: "unavailable"
    id: "timer_ended"
  
  # Alexa timer alarm events (backup detection)
  - platform: state
    entity_id:
      - binary_sensor.echo_dot_kitchen_timer
      - binary_sensor.echo_dot_atlas_room_timer
      - binary_sensor.bose_bedroom_timer
      - binary_sensor.bose_office_timer
    to: "on"
    id: "timer_alarm"

condition:
  - condition: template
    value_template: "{{ trigger.to_state is not none and trigger.from_state is not none }}"

action:
  - choose:
      # Timer Started Actions
      - conditions:
          - condition: trigger
            id: "timer_started"
        sequence:
          # Determine timer context and location
          - variables:
              timer_location: >
                {% set entity = trigger.entity_id %}
                {% if 'kitchen' in entity %}
                  kitchen
                {% elif 'atlas_room' in entity %}
                  atlas_room  
                {% elif 'bedroom' in entity %}
                  bedroom
                {% elif 'office' in entity %}
                  office
                {% else %}
                  unknown
                {% endif %}
              timer_duration: "{{ trigger.to_state.state }}"
              current_hour: "{{ now().hour }}"
              
          # Smart responses based on location and time
          - choose:
              # Kitchen timers - Likely cooking
              - conditions:
                  - condition: template
                    value_template: "{{ timer_location == 'kitchen' }}"
                sequence:
                  - service: script.turn_on
                    target:
                      entity_id: script.intelligent_scene_selector
                    data:
                      variables:
                        context: "cooking"
                        zone: "kitchen"
                  - service: tts.cloud_say
                    target:
                      entity_id: media_player.echo_dot_kitchen
                    data:
                      message: >
                        Kitchen timer set for {{ timer_duration }}. 
                        Optimizing kitchen environment for food preparation.
                        The spice will be perfectly timed.
                  - service: logbook.log
                    data:
                      name: "Sietch Kitchen Intelligence"
                      message: "Timer set for {{ timer_duration }} - Kitchen scene activated for cooking preparation"
              
              # Atlas room timers - Entertainment or relaxation
              - conditions:
                  - condition: template
                    value_template: "{{ timer_location == 'atlas_room' }}"
                sequence:
                  - service: script.turn_on
                    target:
                      entity_id: script.intelligent_scene_selector
                    data:
                      variables:
                        context: "entertainment"
                        zone: "atlas_room"
                  - service: tts.cloud_say
                    target:
                      entity_id: media_player.echo_dot_atlas_room
                    data:
                      message: >
                        Atlas room timer confirmed for {{ timer_duration }}.
                        Navigation center optimized for your activity.
                        Time flows like sand across the desert maps.
              
              # Bedroom timers - Rest or preparation
              - conditions:
                  - condition: template
                    value_template: "{{ timer_location == 'bedroom' }}"
                sequence:
                  - choose:
                      # Evening/night timers
                      - conditions:
                          - condition: template
                            value_template: "{{ current_hour | int >= 20 or current_hour | int <= 6 }}"
                        sequence:
                          - service: script.turn_on
                            target:
                              entity_id: script.night_security_protocol
                          - service: light.turn_on
                            target:
                              area_id: bedroom
                            data:
                              brightness: 50
                              color_temp: 454
                          - service: tts.cloud_say
                            target:
                              entity_id: media_player.bose_bedroom
                            data:
                              message: >
                                Rest timer set for {{ timer_duration }}.
                                Night protocols engaged. The Sietch watches while you rest.
                    default:
                      - service: tts.cloud_say
                        target:
                          entity_id: media_player.bose_bedroom
                        data:
                          message: "Timer confirmed for {{ timer_duration }}. Maintaining optimal rest environment."
              
              # Office timers - Work productivity
              - conditions:
                  - condition: template
                    value_template: "{{ timer_location == 'office' }}"
                sequence:
                  - service: script.turn_on
                    target:
                      entity_id: script.intelligent_scene_selector
                    data:
                      variables:
                        context: "work"
                        zone: "office"
                  - service: tts.cloud_say
                    target:
                      entity_id: media_player.bose_office
                    data:
                      message: >
                        Productivity timer engaged for {{ timer_duration }}.
                        Mentat focus protocols activated. Let efficiency flow.

      # Timer Ended Actions  
      - conditions:
          - condition: trigger
            id: "timer_ended"
        sequence:
          - variables:
              timer_location: >
                {% set entity = trigger.entity_id %}
                {% if 'kitchen' in entity %}
                  kitchen
                {% elif 'atlas_room' in entity %}
                  atlas_room
                {% elif 'bedroom' in entity %}
                  bedroom  
                {% elif 'office' in entity %}
                  office
                {% else %}
                  unknown
                {% endif %}
              current_hour: "{{ now().hour }}"
              activity_level: "{{ states('sensor.fremen_activity_level') | int }}"
          
          # Context-aware timer completion responses
          - choose:
              # Kitchen timer completion
              - conditions:
                  - condition: template
                    value_template: "{{ timer_location == 'kitchen' }}"
                sequence:
                  - service: tts.cloud_say
                    target:
                      entity_id: media_player.echo_dot_kitchen
                    data:
                      message: >
                        Kitchen timer complete. 
                        {% if current_hour | int >= 17 and current_hour | int <= 20 %}
                        The evening meal preparation phase is finished.
                        {% elif current_hour | int >= 6 and current_hour | int <= 10 %}
                        Morning sustenance preparation complete.
                        {% else %}
                        Food preparation cycle finished.
                        {% endif %}
                        Check your creation, the spice has been properly timed.
                  - service: light.turn_on
                    target:
                      area_id: kitchen
                    data:
                      brightness: 255
                      color_temp: 250
                  - delay: "00:00:30"
                  - service: script.turn_on
                    target:
                      entity_id: script.intelligent_scene_selector
                    data:
                      variables:
                        context: "normal"
                        zone: "kitchen"
              
              # Atlas room timer completion
              - conditions:
                  - condition: template
                    value_template: "{{ timer_location == 'atlas_room' }}"
                sequence:
                  - service: tts.cloud_say
                    target:
                      entity_id: media_player.echo_dot_atlas_room
                    data:
                      message: >
                        Timer finished in the navigation center.
                        {% if activity_level > 70 %}
                        High activity detected - maintaining active environment.
                        {% elif current_hour | int >= 20 %}
                        Evening protocols suggest transition to rest preparation.
                        {% else %}
                        Atlas room restored to standard configuration.
                        {% endif %}
                        The maps of time continue to unfold.
              
              # Bedroom timer completion
              - conditions:
                  - condition: template
                    value_template: "{{ timer_location == 'bedroom' }}"
                sequence:
                  - service: tts.cloud_say
                    target:
                      entity_id: media_player.bose_bedroom
                    data:
                      message: >
                        Rest area timer complete.
                        {% if current_hour | int >= 22 or current_hour | int <= 6 %}
                        Night cycle continues. The Sietch maintains its watch.
                        {% elif current_hour | int >= 6 and current_hour | int <= 9 %}
                        Dawn protocols suggest beginning daily preparations.
                        {% else %}
                        Rest period finished. Energy restored.
                        {% endif %}
                  - choose:
                      - conditions:
                          - condition: template
                            value_template: "{{ current_hour | int >= 22 or current_hour | int <= 6 }}"
                        sequence:
                          - service: light.turn_off
                            target:
                              area_id: bedroom
                      - conditions:
                          - condition: template
                            value_template: "{{ current_hour | int >= 6 and current_hour | int <= 9 }}"
                        sequence:
                          - service: script.turn_on
                            target:
                              entity_id: script.morning_startup_routine
              
              # Office timer completion  
              - conditions:
                  - condition: template
                    value_template: "{{ timer_location == 'office' }}"
                sequence:
                  - service: tts.cloud_say
                    target:
                      entity_id: media_player.bose_office
                    data:
                      message: >
                        Productivity timer cycle complete.
                        {% if activity_level > 80 %}
                        High focus session finished - consider brief restoration.
                        {% elif current_hour | int >= 17 %}
                        Work day protocols suggest transition preparation.
                        {% else %}
                        Focus period concluded. Mentat efficiency maintained.
                        {% endif %}
                        Knowledge builds like layers of sand and time.
                  - service: script.turn_on
                    target:
                      entity_id: script.intelligent_scene_selector
                    data:
                      variables:
                        context: "break"
                        zone: "office"

      # Timer Alarm Backup
      - conditions:
          - condition: trigger
            id: "timer_alarm"
        sequence:
          - service: notify.mobile_app_tori_phone_2
            data:
              message: "Alexa timer alarm detected - Smart responses may have activated"
              title: "Sietch Timer System"

  # Log all timer events for learning
  - service: logbook.log
    data:
      name: "Sietch Timer Intelligence"  
      message: >
        Timer event: {{ trigger.id }} | 
        Location: {{ timer_location | default('unknown') }} |
        Activity: {{ states('sensor.fremen_activity_level') }}% |
        Time: {{ now().strftime('%H:%M') }}

mode: parallel
max: 20