id: person_leaves_home
alias: Person Leaves Home
description: Sietch Sealed - Desert Patrol Departure
trigger:
- platform: state
  entity_id: person.tori_myers
  to: not_home
  for: 00:05:00
action:
- service: input_boolean.turn_on
  target:
    entity_id: input_boolean.enhanced_security_mode
- service: switch.turn_off
  target:
    entity_id: switch.front_door_led
- service: notify.mobile_app_tori_phone_2
  data:
    message: Sietch sealed. May your journey across the dunes be blessed with safe
      return.