alias: "Occupancy Climate Control"
description: "Stillsuit occupancy-based climate optimization"
mode: single

trigger:
  - platform: state
    entity_id: binary_sensor.house_occupied

variables:
  occupancy: "{{ is_state('binary_sensor.house_occupied', 'on') }}"
  energy_score: "{{ states('sensor.energy_independence_score') | float(80) }}"
  current_temp: "{{ state_attr('weather.home', 'temperature') or 72 }}"

action:
  # Log occupancy change
  - service: logbook.log
    data:
      name: "Stillsuit Climate Control"
      message: "Occupancy changed: {{ 'Occupied' if occupancy else 'Vacant' }}"

  # Occupied optimization
  - if:
      - condition: template
        value_template: "{{ occupancy }}"
    then:
      # Comfort mode when occupied
      - service: climate.set_preset_mode
        data:
          entity_id: climate.home
          preset_mode: "comfort"

      # Notify of comfort activation
      - service: notify.mobile_app_tori_phone_2
        data:
          title: "ðŸ  Stillsuit: Occupied Mode"
          message: "Sietch occupied. Comfort protocols engaged. Temperature optimizing for presence."

  # Vacant optimization
  - if:
      - condition: template
        value_template: "{{ not occupancy }}"
    then:
      # Energy conservation when vacant
      - service: climate.set_preset_mode
        data:
          entity_id: climate.home
          preset_mode: "eco"

      # Adjust temperature for conservation
      - if:
          - condition: template
            value_template: "{{ current_temp > 75 }}"
        then:
          # Allow warmer when vacant in summer
          - service: climate.set_temperature
            data:
              entity_id: climate.home
              temperature: 78
        else:
          # Allow cooler when vacant in winter
          - service: climate.set_temperature
            data:
              entity_id: climate.home
              temperature: 65

      # Notify of conservation mode
      - service: notify.mobile_app_tori_phone_2
        data:
          title: "ðŸŒ¿ Stillsuit: Conservation Mode"
          message: "Sietch vacant. Energy conservation protocols active. Water and power preserved."